# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site 这里的配置，哪项配置反映在哪里，可以参考我的博客
title: Fancye # 站点名，站点左上角
subtitle: "全栈攻城狮修炼中..." # 副标题，站点左上角
description: "Fancye's blog,Java,Python" # 给搜索引擎看的，对站点的描述，可以自定义
author: Fancye # 在站点左下角可以看到
email: lvsedehuanxiang@163.com # 你的联系邮箱
language: zh-Hans # 中国人，用中文
timezone: Asia/ShangHai

# URL # 这项暂不配置，绑定域名后，欲创建sitemap.xml需要配置该项
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://baininghan.com
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing # 文字布局、写作格式的定义，不修改
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false # To preview your site with drafts
post_asset_folder: false # Put all images and other assets in source folder
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives # 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination # 每页显示文章数，可以自定义
## Set per_page to 0 to disable pagination
per_page: 5
api_posts_per_page: 5
pagination_dir: page

# Disqus # Disqus插件，我们会替换成“多说”，不修改
disqus_shortname: false
duoshuo_shortname: fancye
# Extensions # 这里配置站点所用主题和插件，暂时默认，后面会介绍怎么修改
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
plugins:
- hexo-generator-feed
- hexo-generator-sitemap
- hexo-qiniu-sync
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: next ##yilia ## landscape # coney

exclude_generator:

#七牛云存储设置
##offline       是否离线. 离线状态将使用本地地址渲染
##sync          是否同步
##bucket        空间名称.
##access_key    上传密钥AccessKey
##secret_key    上传密钥SecretKey
##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步 
##urlPrefix     外链前缀. 
##local_dir     本地目录. ##TODO
##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
qiniu:
  offline: false
  sync: false
  bucket: fancye
  access_key: AccessKey
  secret_key: SecretKey
  dirPrefix: static
  urlPrefix: http://fancye.qiniudn.com/static
  local_dir: source\static
  image: 
    folder: img
  js:
    folder: js
  css:
    folder: css
# Deployment # 站点部署到github上时需要配置
## repository: git@gitcafe.com:fancy-bai/fancye.git
## branch: gitcafe-pages
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: github
  repository: https://github.com/baininghan/fancye.git
  branch: gh-pages
- type: gitcafe
  repository: 
  branch: gitcafe-pages
  
## git-backup
backup:
  type: git
  repository:
    github: git@github.com:baininghan/fancye.git,gh-pages
	
# 头像配置
avatar: /images/fancye.png

# Theme since
since: 2014
## next theme configuration
social: 
  github: https://github.com/baininghan
  #twitter: https://twitter.com/your-user-name
  weibo: http://weibo.com/fancybai01
  #douban: http://douban.com/people/your-user-name
  #zhihu: http://www.zhihu.com/people/your-user-name

friend_link:
  #baininghan: http://baininghan.com
  PureFrog: http://mycodebattle.com/
  秦无邪: http://cppgirl.com/
  小雪: http://wileam.com/
  crifan(网络大牛): http://www.crifan.com/
# EndNexT 主题相关配置 ==========================