menu:
  首页: /
  归档: /archives
  关于: /about
  RSS: /atom.xml
  

widgets:
- search
- category
- tagcloud
- intro
- blogroll

excerpt_link: 阅读全文

plugins:
- hexo-generator-feed

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-41207871-1
rss: http://baininghan.github.io/fancye/atom.xml

swiftype_search:
	enable: true